### PR TITLE
Add control mode handling 

### LINKED ISSUE #13: Error while compiling branch "addControlModes"
I checked out this branch, I run make uninstall and I removed the build directory. Then, I tried to compile the repo. I got the following error:

 ```
Building CXX object CMakeFiles/bridge_ihmc_ors.dir/yarp_plugin_bridge_ihmc_ors.cpp.o
In file included from /home/gabri/Software/gitHub/robotology-playground/ihmc-ors-yarp/build/yarp_plugin_bridge_ihmc_ors.cpp:10:0:
/home/gabri/Software/gitHub/robotology-playground/ihmc-ors-yarp/src/BridgeIHMCORS.h:142:10: error: ‘mutex’ in namespace ‘std’ does not name a type
     std::mutex m_jointORSControlModeMutex;

```
Isn't it because `mutex` is actually a `yarp` and not `std` class?

### PR DESCRIPTION
**Pull request by traversaro**
Ad discussed in the iteration meeting. For details on how the new lifecycle works, please see the updated README . 
I also added a working test using RTF, but we cannot enable if on Travis for now because it depends on a few PR that need to be merged. 

Fixes #13

### CODE REVIEW

**Comment by traversaro** [comment]
cc @dljsjr @georgwi this PR modifies the IDL message, if you have a local copy of it somewhere please update it.

**Review by gabrielenava — COMMENTED** [review]
I got an error while trying to compile the repo. It may be me, because travis actually compiles, but I'm going to open an issue anyway.

**Comment by traversaro** [comment]
Thanks for the note. Actually [std::mutex](http://en.cppreference.com/w/cpp/thread/mutex) is indeed an actual class introduced in C++11, but I was missing the proper `#include <mutex>` (on macOS it was probably working thanks to some transitive includes). I switched all the muteces to `std::mutex` as it is the more future-proof option.

**Comment by traversaro** [comment]
I now rebased on master, so we can rely on Travis to catch this kind of compilation problems.

**Comment by dljsjr** [comment]
Looks sane enough.

**Comment by traversaro** [comment]
@gabrielenava can you merge? Thanks!

**Comment by gabrielenava** [comment]
done!

**Pull request merged**
