### PR TITLE
Additional reading of IMUs and FTs

### LINKED ISSUE #8: Publish IMU measurements

### PR DESCRIPTION
**Pull request by francesco-romano**
This fixes #8 and #9 

Still pending: IMU in iCub yields RPY measurements, while the IDL is expecting a quaternion.
What should we do? @traversaro 

Note: on closing I get a segfault (happening also on master)

### CODE REVIEW

**Comment by traversaro** [comment]
> Still pending: IMU in iCub yields RPY measurements, while the IDL is expecting a quaternion. 

There are some function in YARP_math related for converting back and forth between RPY and quaternion, I would use those. 

One comment: IHMC is expecing FT measurements without any offset, and it is actually considering them to be **external** forces. So the actual idea was to read the estimated external F/T coming from wholebodydynamics and send them through the IHMC bridge.

**Comment by traversaro** [comment]
@francesco-romano Can you open a separated issue for the segfault while closing? Thanks!

**Comment by francesco-romano** [comment]
@traversaro probably the FT name is misleading, but I am reading wholeBodyDynamics wrenches (see the config file)

**Comment by francesco-romano** [comment]
Regarding RPY: do you mean a "concatenation" of 

`yarp::math::ypr2dcm` and `Quaternion::fromRotationMatrix` ?

**Comment by traversaro** [comment]
> @traversaro probably the FT name is misleading, but I am reading wholeBodyDynamics wrenches (see the config file).

Ok great!

**Comment by francesco-romano** [comment]
@georgwi : the only missing part is how to output the orientation of the IMU.
To be clear on this, given the orientation of the IMU w.r.t. a certain world frame, i.e. `w_R_imu`, how do you expect the resulting quaternion? 
Note that the YARP driver outputs RPY parametrisation

**Comment by georgwi** [comment]
The orientation of the IMU frame w.r.t. the world frame as a quaternion would be perfect. If you prefer passing the RPY representation to us we can handle the conversion on our end also.

**Comment by francesco-romano** [comment]
Hi @georgwi. Just to be clear,
we usually use the following mapping between quaternion and associated rotation matrix:
```
w_R_s = 1_3 + 2 s r^ + 2(r^)*(r^)
```
where `1_3` is the identity matrix 3x3, `s` is the real part of the quaternion, `r` is the imaginary part and `r^` is the 3x3 skew symmetric matrix.

Note that there exist an alternative formulation:
```
w_R_s = 1_3 - 2 s r^ + 2(r^)*(r^)
```
so we'd like to be sure the one you are using.

A part from the orientation, everything else is ready, so I think you can also start setting up the Java part

**Comment by georgwi** [comment]
I looked at our conversion code and it looks like we are using the same as you (the first one)!

**Comment by francesco-romano** [comment]
Ok, done.

Ready for review and testing (cc @traversaro @gabrielenava @georgwi )

**Pull request merged**
